<a href="https://colab.research.google.com/github/MaciejAutuch/Visual_Recognition_Project/blob/main/PipeLine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Liblaries

In [ ]:
pip install mafaextractor

Requirement already satisfied: mafaextractor in /usr/local/lib/python3.7/dist-packages (0.1.1)
Requirement already satisfied: numpy<2.0.0,>=1.19.1 in /usr/local/lib/python3.7/dist-packages (from mafaextractor) (1.21.6)
Requirement already satisfied: pandas<2.0.0,>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from mafaextractor) (1.3.5)
Requirement already satisfied: scipy<2.0.0,>=1.5.2 in /usr/local/lib/python3.7/dist-packages (from mafaextractor) (1.7.3)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.1.0->mafaextractor) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.1.0->mafaextractor) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.1.0->mafaextractor) (1.15.0)

In [ ]:
import pandas as pd
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
from mafaextractor import extract_mafa
from google.colab import drive

Files Upload and Imports

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
!unzip /content/gdrive/MyDrive/AIdata/train-images.zip -d'/content/train_images'

Archive:  /content/gdrive/MyDrive/AIdata/train-images.zip
replace /content/train_images/images/train_00000001.jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
!unzip /content/gdrive/MyDrive/AIdata/MAFA-Label-Test.zip

Archive:  /content/gdrive/MyDrive/AIdata/MAFA-Label-Test.zip
replace LabelTestAll.mat? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
!unzip /content/gdrive/MyDrive/AIdata/MAFA-Label-Train.zip

Archive:  /content/gdrive/MyDrive/AIdata/MAFA-Label-Train.zip
replace LabelTrainAll.mat? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
!unzip /content/gdrive/MyDrive/AIdata/test-images.zip -d '/content/test_images'

Archive:  /content/gdrive/MyDrive/AIdata/test-images.zip
replace /content/test_images/images/test_00000001.jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename:

Label Decoding and Processing

In [ ]:
from mafaextractor import extract_mafa

train_label = extract_mafa('/content/LabelTrainAll.mat')
test_label = extract_mafa('/content/LabelTestAll.mat')

In [ ]:
#checking the labels
pd.set_option('display.max_columns', None)
train_label

,img_name,x_face_min,y_face_min,face_width,face_height,left_eye_x,left_eye_y,right_eye_x,right_eye_y,occ_width,occ_height,occ_type,occ_degree,gender,race,orientation,glasses_width,glasses_height,x_face_max,y_face_max,x_occ_min,y_occ_min,x_occ_max,y_occ_max,x_glasses_min,x_glasses_max,y_glasses_min,y_glasses_max
0,train_00000001.jpg,95,160,91,91,113,177,158,172,82,89,1,3,1,1,3,-1,-1,186,251,102,186,177,249,-1,-1,-1,-1
1,train_00000002.jpg,107,82,66,66,129,95,156,96,65,56,2,3,1,1,3,-1,-1,173,148,112,99,172,138,-1,-1,-1,-1
2,train_00000003.jpg,56,170,185,185,140,198,196,208,147,182,1,3,1,1,4,-1,-1,241,355,97,226,203,352,-1,-1,-1,-1
3,train_00000004.jpg,162,208,71,71,182,229,203,238,46,70,2,3,1,1,2,-1,-1,233,279,169,234,208,278,-1,-1,-1,-1
4,train_00000005.jpg,86,69,99,99,134,93,165,98,76,97,1,1,2,1,4,-1,-1,185,168,92,139,162,166,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29447,train_00025872.jpg,44,4,107,107,67,21,119,20,101,100,2,3,2,2,3,-1,-1,151,111,53,35,145,104,-1,-1,-1,-1
29448,train_00025873.jpg,31,3,80,80,58,18,90,29,69,79,2,3,2,2,3,-1,-1,111,83,35,38,100,82,-1,-1,-1,-1
29449,train_00025874.jpg,14,28,83,83,33,51,72,56,80,87,2,2,2,2,3,-1,-1,97,111,18,81,94,115,-1,-1,-1,-1
29450,train_00025875.jpg,38,4,72,72,60,23,93,21,65,77,2,3,2,2,3,-1,-1,110,76,40,33,103,81,-1,-1,-1,-1
29451,train_00025876.jpg,72,16,34,34,79,26,96,26,32,36,2,3,1,2,3,104,31,106,50,76,31,104,52,148,252,36,67

In [ ]:
#checking the labels
test_label

,img_name,x_face_min,y_face_min,face_width,face_height,face_type,occ_width,occ_height,occ_type,occ_degree,gender,race,orientation,glasses_width,glasses_height,x_face_max,y_face_max,x_occ_min,y_occ_min,x_occ_max,y_occ_max,x_glasses_min,x_glasses_max,y_glasses_min,y_glasses_max
0,test_00000001.jpg,2694.0,1211.0,353.0,353.0,1.0,144.0,337.0,2.0,3.0,2.0,2.0,1.0,-1.0,-1.0,3047.0,1564.0,2703.0,1316.0,2838.0,1548.0,-1.0,-1.0,-1.0,-1.0
1,test_00000001.jpg,1754.0,1449.0,68.0,68.0,3.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1822.0,1517.0,1753.0,1448.0,1753.0,1448.0,-1.0,-1.0,-1.0,-1.0
2,test_00000002.jpg,113.0,95.0,226.0,226.0,1.0,181.0,221.0,1.0,3.0,1.0,2.0,3.0,-1.0,-1.0,339.0,321.0,122.0,166.0,294.0,316.0,-1.0,-1.0,-1.0,-1.0
3,test_00000003.jpg,352.0,114.0,151.0,151.0,1.0,137.0,135.0,1.0,3.0,2.0,2.0,3.0,-1.0,-1.0,503.0,265.0,369.0,159.0,489.0,249.0,-1.0,-1.0,-1.0,-1.0
4,test_00000003.jpg,799.0,217.0,139.0,139.0,2.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,938.0,356.0,798.0,216.0,798.0,216.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10028,test_00004931.jpg,135.0,51.0,285.0,285.0,1.0,280.0,267.0,1.0,3.0,2.0,2.0,3.0,-1.0,-1.0,420.0,336.0,189.0,159.0,415.0,318.0,-1.0,-1.0,-1.0,-1.0
10029,test_00004932.jpg,38.0,120.0,285.0,285.0,1.0,255.0,258.0,1.0,3.0,2.0,2.0,3.0,-1.0,-1.0,323.0,405.0,68.0,213.0,293.0,378.0,-1.0,-1.0,-1.0,-1.0
10030,test_00004933.jpg,80.0,121.0,245.0,245.0,1.0,238.0,242.0,1.0,3.0,2.0,2.0,3.0,-1.0,-1.0,325.0,366.0,130.0,202.0,318.0,363.0,-1.0,-1.0,-1.0,-1.0
10031,test_00004934.jpg,148.0,266.0,276.0,276.0,1.0,265.0,248.0,1.0,3.0,2.0,2.0,3.0,-1.0,-1.0,424.0,542.0,186.0,334.0,413.0,514.0,-1.0,-1.0,-1.0,-1.0
10032,test_00004935.jpg,110.0,98.0,318.0,318.0,1.0,313.0,302.0,1.0,3.0,2.0,2.0,3.0,-1.0,-1.0,428.0,416.0,183.0,222.0,423.0,400.0,-1.0,-1.0,-1.0,-1.0

In [ ]:
# drop pictures with face width or height lower than 32 pixels and minus values for coordinates 
def df_standardization(df, new_df):
  new_df = df.drop(df[(df['face_width'] < 32) |
                      (df['face_height'] < 32) |
                      (df['x_face_min'] < 0) |
                      (df['y_face_min'] < 0)
                         ].index, inplace=True)

In [ ]:
df_standardization(test_label, test_label)

In [ ]:
df_standardization(train_label, train_label)

In [ ]:
# Plan:
#print image
#see how crop function works (crop image and then print it to see changes)
#make a loop that does 3 trings: 1 changes a photo to a np array, crops the photo based on the values from the label table, iterates through test and train data

Data Processing and Standarization

In [ ]:
# Next steps
# Look for the facial recognition algorythm
# See how it can be applied 
# Create a simple model as a benchmark for predictions 
# Start thinking about the possible code application

In [ ]:
os.mkdir('/content/test_images_processed/')

FileExistsError: ignored

In [ ]:
os.mkdir('/content/train_images_processed/')

In [ ]:
# function to trim the photos, it takes the label data frame, orginal image pathway, new image pathway and information about df rows and index
# add an error handling for pictures so that there is no problem with the picture size 

def trim_function(df, op_path, sv_path, row, nr):
  path = op_path + row['img_name']
  img = cv2.imread(path) # opening the photo and changing to array to make changes
  x = int(row['x_face_min'])
  y = int(row['y_face_min'])
  w = int(row['face_width'])
  h = int(row['face_height'])
  new_img = img[y:y+h, x:x+w] # using previously defined coordinates to trim the photo
  new_img = cv2.resize(new_img, (32, 32), interpolation = cv2.INTER_AREA)
  return cv2.imwrite(str(sv_path + 'train_' + str(nr) + '.jpg'), img) # returning a trimmed face picture

In [ ]:
#Processing the test photos

for index, row in test_label.iterrows():
  try:
    trim_function(test_label, '/content/test_images/images/', '/content/test_images_processed/', row, index)
  except:
    continue

In [ ]:
#Processing the train photos

for index, row in train_label.iterrows():
  try:
    trim_function(train_label, '/content/train_images/images/', '/content/train_images_processed/', row, index)
  except:
    continue

In [ ]:
img_4 = Image.open('/content/test_images_processed/image_1076')

In [ ]:
plt.imshow(img_4)

In [ ]:
# Create a zipper function that zips the images and enabels it to be saved + save a df that can be used for the later processing

In [ ]:
test_label.loc[test_label['occ_degree'] >= 3, 'occ_degree'] = 1
test_label.loc[test_label['occ_degree'] < 3, 'occ_degree'] = 0

In [ ]:
new_df = test_label['occ_degree']

In [ ]:
new_df

In [ ]:
train_label

In [ ]:
!zip -r /content/file.zip /content/test_images_processed

In [ ]:
!zip -r /content/file.zip /content/train_images_processed

In [ ]:
# create mask label in test dataset

condition = [(test_label['occ_type'] == 1) |
             ((test_label['occ_type'] == 2) & (test_label['occ_degree'] == 3))]

value = [1]
test_label['face_mask'] = np.select(condition, value)
test_label.head(5)

In [ ]:
# create mask label in train dataset

condition = [(train_label['occ_type'] == 1) |
             ((train_label['occ_type'] == 2) & (train_label['occ_degree'] == 3))]

value = [1]
train_label['face_mask'] = np.select(condition, value)
train_label.head(5)

In [ ]:
#droping disregarded columns in the test label

drop_list =[1627, 1772, 2403, 2404, 2491, 3760, 4048, 4880, 4898, 5295, 5851, 5852, 5854, 6570, 6571, 6572, 6573, 6574, 6575, 6576, 6895, 8502, 8850]

for num in drop_list:
  test_label = test_label.drop(num)

In [ ]:
test_labels = test_label['face_mask']
train_labels = train_label['face_mask']

In [ ]:
#save dfs so there is no need to go any of those steps again

In [ ]:
#save zipped files so that the pipeline done its job and can be saved

In [ ]:
train_labels.to_csv('train_labels.csv')
test_labels.to_csv('test_labels.csv')